### PR TITLE
README更新と@types/testing-library__reactの削除

### PR DESCRIPTION
**Pull request by lightsound**
## 変更点

- READMEの更新
- `@types/testing-library__react` が不要なので削除

### CODE REVIEW

**Comment by lightsound** [comment]
@all-contributors please add @lightsound for doc

**Review by ya2s — APPROVED** [review]
👍

**Review by abc123931 — APPROVED** [review]
👍

**Comment by lightsound** [comment]
@all-contributors please add @lightsound for doc

**Pull request merged**
